### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO45_Za_Wolnosc.eden#1]
### Mission:
 - [x] 1. Обзор в description.ext не влазит в строки, разделить и добавить новые (в новой строке добавить OVERVIEW(<номер строки>, <Текст>); Номер строки можно не по порядку, главное чтобы у каждой строки свой уникальный номер был)
 - [x] 2. Название миссии должно быть в формате CO45 Навзание (сейчас там CO_45_Za_Wolnosc!)
 - [x] 3. В брифинге Поддержка -- каждый ассет нужно на новой линии.
 - [x] 4. В брифинге Сигналы -- ДВ нет, и про КВ ни слова. Если КВ есть то указать дефолтные каналы.
 - [x] 5. Для всех объектов с которым не нужно взаимодействовать выключить симуляцию (открыть свойства - Special States - Enable simulation - убрать галочку)
 - [x] 6. Некоторые воронки на севере города висят в воздухе (можно приклеить к земле через ctrl + q )
 - [x] 7. Вообще говоря -- а какого черта все дома popierdoliło так? Я мож просмотрел брифинг. но про землятрясения не помню. Там же можно выключить вырававние по террейну и покрутить объект - он выровняется по горизонту
![image](https://user-images.githubusercontent.com/9357337/112716298-905c5000-8ef6-11eb-845e-9e59e3e2e16d.png)

### tSF:
 - [x] 1.  Миссия завершается успехом на 10ой секунде (В зоне изначально нет ни одного Вест юнита, а дунай стартует в течение первых 30 секунд (чтобы чуток снизить нагрузку на сервер при запуске). Поэтому в MissionConditions можно добавить проверку инициализации дуная: 
 ```
MissionCondition1 = [ 
  "WIN", 
  { [WinTrigger, "west", "", "< 3"] call dzn_fnc_ccUnits && !isNil "dzn_dynai_initialized" && { dzn_dynai_initialized } }, 
  "All objectives done"
];
```
Ну или просто проверить что прошло уже некоторое время  со старта -- time > 60.
Но сначала починить дунаевские зоны, т.к. ничег **в принципе** и не спавнится в городе.
 - [x] 2. Если у ФАРП и ЦЦП такие маленькие зоны, то можешь просто удалить связанный триггер. Тогда ццп и фарп будут спавнится прямо на месте размещения геймлоджика
 - [x] 3. tSF_module_ArtillerySupport включен, но в брифинге нет упоминания.
 - [x] 4. В IntroText можно дату не менять, а оставлять из редактора (тогда просто оставляешь дефолтное "%1/%2/%3")

### Dynai:
 - [x] 1. Крайне нежелательно делать группы где часть юнитов ИНДУР. Арма боты начинают очень неохотно ходить когда ктото отстает или застряд.
 - [x] 2. Пожалуйста, используйте UI хелпер для дунайных зон! Вот эта хуйня это такая хуйня что я не знаю: 
https://github.com/rempopo/CO45_Za_Wolnosc.eden/blob/70023b8afa82aac39bcfda8447ba8c97bcf98b14/dzn_dynai/Zones.sqf#L152-L176
^ Тут и скобочки проебаны и аж целая строка с настройкой поведения (скорость, бехавиор и т.п.)
https://github.com/rempopo/CO45_Za_Wolnosc.eden/blob/70023b8afa82aac39bcfda8447ba8c97bcf98b14/dzn_dynai/Zones.sqf#L30-L34
^ Тут напроебано скобочек тоже
 - [x] 3. Зона Forest2 активирована со старта, но зачемто условие активации имеет. Нужно или выключить на старте ее или удалить условие
 - [x] 4. Часть зон не имеют конфига, часть - есть в конфиге но не имеют зон:
 ![image](https://user-images.githubusercontent.com/9357337/112715981-bbde3b00-8ef4-11eb-9d38-c4d86e721e46.png)

### Gear:
 - [x] 1. Включен режим редактирования
 - [x] 2. У первого слота нема кита (1-1 Доводца обдристаны), судя по всему у прочих командиров аналогично. В GAT роли с @Wilk-1, а в редакторе без.

**Comment by Arsdor** [comment]
**Mission**
1. fixed
2. fixed
3. fixed
4. fixed
5. fixed
6. fixed
7. не пофикшено, так как при отвязке от террейна у большей части домов возникает проблема, аналогичная 6
**Tsf**

1. Fixed
2. fixed
3. fixed
4. fixed
**Dynai**

1. Fixed
2. Fixed
3. Fixed
4. Fixed
**Gear**

1. Fixed
2. Fixed
